### ISSUE TITLE
Incopatible with Angular 9

### ISSUE THREAD

**Issue by dmytrodemchenko** [pIvan/file-upload#34] opened 2020-02-07 15:04 UTC
The functionality of the uploader doesn't work with a major version of Angular 9. 
As an example, it through the error in a dev console and as example, you can check it below: 

<img width="1421" alt="Screenshot 2020-02-07 at 17 02 07" src="https://user-images.githubusercontent.com/11888586/74040162-d6d9ad00-49cb-11ea-9ab2-27c924a7ca60.png">

**Comment by pIvan** [comment] 2020-02-07 20:56
Hi @dmytrodemchenko,

can you give me more info about the problem? You just updated project to angular 9
and then all stopped to work?
Did everything work before the update?

**Comment by dmytrodemchenko** [comment] 2020-02-10 09:02
Hi @pIvan,
I just updated the project to Angular 9 and then I got an error in DEV console as attached above. 
Everything before was fine - no issues.  

Could you take a look?

**Comment by pIvan** [comment] 2020-02-10 10:12
Hi @dmytrodemchenko,
today I will make commit.

Kind regards.

**Comment by pIvan** [comment] 2020-02-10 17:01
Hi @dmytrodemchenko,
I just made a test with angular 9 and can't reproduce the same error.
Can you give me some code snippets from HTML and typescript?
And also which version of file-upload do you use?

Thanks

**Comment by dmytrodemchenko** [comment] 2020-02-11 07:46
@pIvan 
It works with fine the latest release

The issue with v1.2.2.

sorry, and thanks for your help!

**Comment by pIvan** [comment] 2020-02-11 20:36
You're welcome @dmytrodemchenko, I'm closing this

**Closed** 2020-02-11 20:36 UTC
